FROM node:20.9.0

WORKDIR /app

COPY package*.json ./

# Install production dependencies
RUN npm ci --only=production

# Copy the rest of the application code
COPY . .

# Build the production version
RUN npm run build

# Set environment variables
ENV PORT=8080

# Expose the port
EXPOSE 8080

# Command to start the application
CMD ["npm", "run", "start"]
